### ISSUE TITLE
Get current holdings sample code question

### ISSUE THREAD

**Issue by HXyL229ZI0gk5u** [BookOps-CAT/bookops-worldcat#95]
I find that the holdings_get_current sample code (https://bookops-cat.github.io/bookops-worldcat/latest/manage_holdings/) only returns the following error, unless the OCLC number is enclosed in quotes:

Traceback (most recent call last):
  File "C:\Users\tosaka\PycharmProjects\DataSync2\main.py", line 20, in <module>
    response = session.holdings_get_current(oclcNumbers=123456789)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tosaka\Anaconda3\envs\pythonProject\Lib\site-packages\bookops_worldcat\metadata_api.py", line 879, in holdings_get_current
    vetted_numbers = verify_oclc_numbers(oclcNumbers)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tosaka\Anaconda3\envs\pythonProject\Lib\site-packages\bookops_worldcat\utils.py", line 84, in verify_oclc_numbers
    raise InvalidOclcNumber(
bookops_worldcat.errors.InvalidOclcNumber: Argument 'oclcNumbers' must be a list or comma separated string of valid OCLC #s.

**Comment by HXyL229ZI0gk5u** [comment]
Putting in brackets and making a list seems to return the output as expected:

response = session.holdings_get_current(oclcNumbers=[123456789])
